
spring:
  application:
    name: securityOauth2

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liMTxafnKTsyJxlW
            client-secret: 34c92e8f006f0274775258e58d507a6a1f0526ca
#          scope: profile, email
#          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#          client-name: Google
#          scope: read:user
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user

server:
  port: 9090
