server:
  port: 9091

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/master
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/realms/master/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  auth:
    converter:
      resource-id: demo
      principle-attribute: preferred_username

keycloak:
  server-url: http://localhost:8080
  realm: master
  client-id: demo
  admin:
    username:  KeyClock
    password: P@ssw0rd()KeyClock
